# Generated by Django 4.1.7 on 2023-02-28 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre y apellido')),
                ('dni', models.CharField(max_length=8, verbose_name='DNI')),
                ('address', models.CharField(max_length=100, verbose_name='Dirección')),
                ('cellphone', models.CharField(max_length=10, verbose_name='Teléfono')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='odoo.client', verbose_name='Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('administrativo', 'Administrativo'), ('tecnico', 'Técnico')], max_length=20, verbose_name='Motivo')),
                ('description', models.TextField(max_length=200, verbose_name='Descripción')),
                ('status', models.CharField(choices=[('ingresado', 'Ingresado'), ('en_proceso', 'En Proceso'), ('resuelto', 'Resuelto')], max_length=20, verbose_name='Estado')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='odoo.service', verbose_name='Servicio')),
            ],
        ),
    ]
