# Generated by Django 4.1.7 on 2023-02-28 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odoo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='lat',
            field=models.CharField(max_length=10, null=True, verbose_name='Latitud'),
        ),
        migrations.AddField(
            model_name='service',
            name='lng',
            field=models.CharField(max_length=10, null=True, verbose_name='Longitud'),
        ),
        migrations.AddField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[(1, '3 Megas'), (2, '5 Megas')], default=1, max_length=20, verbose_name='Tipo de Servicio'),
            preserve_default=False,
        ),
    ]
