# Generated by Django 4.1.7 on 2023-02-28 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odoo', '0003_alter_service_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='credit',
            field=models.FloatField(default=0, verbose_name='Deuda'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='lat',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Latitud'),
        ),
        migrations.AlterField(
            model_name='service',
            name='lng',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Longitud'),
        ),
    ]
