# Generated by Django 4.1.7 on 2023-02-28 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odoo', '0004_client_credit_alter_service_lat_alter_service_lng'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='is_done',
            field=models.BooleanField(default=0, verbose_name='Resuelto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='claim',
            name='status',
            field=models.CharField(choices=[('ingresado', 'Ingresado'), ('asignado', 'Asignado'), ('en_proceso', 'En Proceso')], default='ingresado', max_length=20, verbose_name='Estado'),
        ),
    ]
