# Generated by Django 4.1.7 on 2023-02-28 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odoo', '0005_claim_is_done_alter_claim_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim',
            name='is_done',
        ),
        migrations.AddField(
            model_name='service',
            name='has_active_claim',
            field=models.BooleanField(default=0, verbose_name='Tiene reclamo activo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='claim',
            name='status',
            field=models.CharField(choices=[('ingresado', 'Ingresado'), ('asignado', 'Asignado'), ('en_proceso', 'En Proceso'), ('terminado', 'Terminado')], default='ingresado', max_length=20, verbose_name='Estado'),
        ),
    ]
